[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/:slug"
  to = "/public/index.html"
  status = 200
  force = true
